### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot use 'in' operator to search for 'clientId' in undefined

### ISSUE THREAD

**Issue by sot232** [byuweb/byu-browser-oauth-implicit#10]
Your team may be aware of it, but I am posting it just in case.

Everything worked just fine a few hours ago. I suddenly received the error message.

Is there something I need to do in order to fix the error? Or will you fix it?

`Unhandled Rejection (TypeError): Cannot use 'in' operator to search for 'clientId' in undefined`

`resolveConfig`
`../src/implicit-grant.js:55:6`

```
  52 | }
  53 | 
  54 | function resolveConfig(rules, location) {
> 55 |   if ('clientId' in rules) {
     |      ^  56 |     return rules;
  57 |   }
  58 | 
```

`Module.configure`
`../src/implicit-grant.js:36:14`

```
  33 |  * @param location
  34 |  */
  35 | export async function configure(cfgOrRules, location = window.location) {
> 36 |   const cfg = resolveConfig(cfgOrRules, location);
     |              ^  37 |   const globalConfig = window[GLOBAL_CONFIG_KEY];
  38 | 
  39 |   const config = Object.assign({
```

Thank you.

**Comment by snelg** [comment]
Just pushed the official 1.0.0 release, that's what broke for you, sorry. I'll fix the bug, but for immediate fix on your end you can have your code explicitly point to the previous release, 0.2.3
Change
```
https://cdn.byu.edu/browser-oauth-implicit/latest/implicit-grant.js
```
to
```
https://cdn.byu.edu/browser-oauth-implicit/0.2.3/implicit-grant.js
```

**Comment by snelg** [comment]
@sot232 I might need a little more context for how you're setting it up in your code.
What are you passing to `implicit.configure()`?

**Comment by sot232** [comment]
@snelg The website is working again as soon as I correctly use implicit.configure parameters.

To be honest with you, I didn't pass any parameters. However, it worked. I knew I was supposed to pass some values. I was ignoring it.

Thank you for your help!

**Comment by snelg** [comment]
You did help me find a bug anyhow :)
You can set the config in the global `window` object and then call `implicit.configure()` :

```javascript
window['byu-oauth-implicit-config'] = {
  clientId: "blahblahblahblah",
  callbackUrl: "https://mysite.byu.edu"
}

implicit.configure()
```

But our unit tests were checking if you pass an empty object into the `configure` call, e.g.
```javascript
implicit.configure( { } )
```

I fixed the code to properly handle that *completely* empty `implicit.configure()` call, as long as you set the configuration in `window`
