### ISSUE TITLE
Bearer Token being written to console

### ISSUE THREAD

**Issue by kebowdog** [byuweb/byu-browser-oauth-implicit#13]
Not sure if this is really a security hole, but it feels like it may not be the best idea: the bearer token, byuID of the owner of the app, and other user info is being printed to the console:

![image](https://user-images.githubusercontent.com/19493582/68039285-6cf58d00-fc91-11e9-9de4-ec22dc1d4d7b.png)

**Comment by snelg** [comment]
Good point. Default logging level bumped up to "error" instead of "info".
