### ISSUE TITLE
Looking for a way to not redirect on logout

### ISSUE THREAD

**Issue by trey-wallis** [byuweb/byu-browser-oauth-implicit#31]
The documentations says this about logout:

```
// Similarly, for logout:
logout().then(({state, token, user, error}) => {
  // If we don't have to redirect the browser to log the user in, you can respond to the completed
  //  login here
});
```

What is the point of chaining the logout promise with .then() is it just for clean up?

I am looking for a way to prevent redirect on logout, but it seems like the oauth setup always redirects on logout.

Do you have any solutions to this?

**Comment by snelg** [comment]
A comment in the code partially explains the problem:

// TODO: WSO2 Identity Server 5.1 allows us to revoke implicit tokens.  Once that's done, we'll need to do this.

BYU never upgraded to WSO2 5.1.
There's no API available to directly revoke a token, so we have to send the user's browser to the WSO2 logout page.

BUT I did add an option that might help, and neglected to update the README. In your config (i.e. along with `clientId`, `callbackUrl`), you can set `logoutRedirect` to specify where the user's browser should redirect after returning from WSO2's logout.

**Comment by snelg** [comment]
Hmm, now that I look at the code again, the default `logoutRedirect` *should* return to the current site if it's not set. So that might not help your particular case.
