### ISSUE TITLE
Double login

### ISSUE THREAD

**Issue by trey-wallis** [byuweb/byu-browser-oauth-implicit#33]
Using this sample code, I get 2 console log statements. This happens on every login

```
import { AuthenticationObserver, login } from '@byuweb/browser-oauth';

const observer = new AuthenticationObserver(({state, token, user, error}) => {
  // React to the change in state
  if (error) {
    // React to authentication error
  } else if (token && user) {
     console.log(token);
    // User is logged-in - start loading data or taking other actions
  } else {
  }
});
```

**Comment by snelg** [comment]
Known issue if you have the "autoRefreshOnTimeout" flag enabled.
It's a workaround for a bug in WSO2. In brief, the "expires" value that WSO2 sends is sometimes slightly incorrect when you grab a token for the very first time. So the code waits a few seconds, and then uses a hidden iframe to refresh the token.
